# Generated by Django 5.1.1 on 2024-09-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="Email"
                    ),
                ),
                ("password", models.CharField(max_length=255, verbose_name="Password")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "first_name",
                    models.CharField(
                        default="", max_length=255, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        default="", max_length=255, verbose_name="Last Name"
                    ),
                ),
                ("age", models.IntegerField(null=True, verbose_name="Age")),
                (
                    "email",
                    models.CharField(default="", max_length=255, verbose_name="Email"),
                ),
                (
                    "role",
                    models.CharField(default="", max_length=255, verbose_name="Role"),
                ),
                ("about_me", models.TextField(default="", verbose_name="About me")),
                (
                    "skills",
                    models.TextField(blank=True, default="[]", verbose_name="Skills"),
                ),
                (
                    "experience",
                    models.TextField(
                        blank=True, default="[]", verbose_name="Experience"
                    ),
                ),
            ],
        ),
    ]
