# Generated by Django 5.1.1 on 2024-09-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="quote",
            field=models.CharField(default="", max_length=255, verbose_name="Quote"),
        ),
    ]
